name: custom_info_window
description: A widget based custom info window for google_maps_flutter package.
version: 1.0.1
repository: https://github.com/abhishekduhoon/custom_info_window
issue_tracker: https://github.com/abhishekduhoon/custom_info_window/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: